name: Manual Build and Deploy
on:
  push:
    branches: [ main ] # 메인에 코드 올릴 때마다 자동 실행
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      - name: Build and push image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_SERVER }}/ca-esg10-api:${{ github.sha }} .
          docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/ca-esg10-api:${{ github.sha }}
